language: java
jobs:
  allow_failures:
  - os: osx
  include:
  - jdk: openjdk8
    os: linux
  - jdk: openjdk11
    os: linux
  - jdk: openjdk11
    os: osx
notifications:
  email:
    recipients:
    - kreberl@uni-trier.de
    on_success: always
    on_failure: always
before_install: gradle installWrapper
cache:
  directories:
  - "$HOME/.m2"
  - "$HOME/.gradle"


    
