language: java
jobs:
  allow_failures:
  - os: osx
  include:
  - jdk: openjdk8
    os: linux
  - jdk: openjdk11
    os: linux
  - jdk: openjdk11
    os: osx
notifications:
  email:
    recipients:
    - kreberl@uni-trier.de
    on_success: always
    on_failure: always
before_install: gradle installWrapper
cache:
  directories:
  - "$HOME/.m2"
  - "$HOME/.gradle"
addons:
  sonarcloud:
    organization: "lucaskreber"
    token:
secure: "mM56IEgz19hW3POEeWNqUX2fiUQlCn7tn4gVwSxnHH2MEQH5eUG3gDMPln83VqsGCla8vHYDoPPMT2mFzMNCSNheAtQSiLsJYiKoPpQLzBZ7yPGwmh4X/dj84nzS5PlgJfZKRdjZezb7iORTKXd328uoW7TebJfQBT8Wclug6RQ0F6BuOi1a6dAr2ItwEKvasmKjoXyX14mzDllN0kTWTzhfj6v0U9Nh8+OLV/LgRjpuuKGRSWo4migCMEn8dDs2l3640O9hpf8/xjTh/2kCQ39oTXLYzcqo4PpiXxsZs4rGGNvhMIgCNAOQpZ3IXISEafIhQ4J2+wOPCLAh9/J8WtSPqWUNszJ7D/KLZiNKY2qo+D+eSYklXQrZTOEO9YzlEj7ha/TkBuMch7aaOI6eIkJ0yUBUHZfnoEWEKFCs450jStsBdI+hE/Tq1MtOhEmqVz2UyzJMBZZj9UR4Dc60hYdLHqOaS73YUtBbHEJsvIU7Tzfd4tjD4SLYcI0/qAigaN4+r/bcvwiAbPd3e7hbuZgHtEGj3M8QSWzMl5nnILiNTl9aCiFtbMJtvytNUfjMPhLjkQapmVDDnNI2R/CNH+P38vYwgoJCLR/mvBFHnn4TM9/n8tuGgdA4ECzlwRyMKF3b9MvTfGTA/ivE+NiK1iKIyF04bvWqq9gp3nuu8IU="
script:
- ./gradlew sonarqube

    
