language: java
jobs:
  allow_failures:
  - os: osx
  include:
  - jdk: openjdk8
    os: linux
  - jdk: openjdk11
    os: linux
  - jdk: openjdk11
    os: osx
notifications:
  email:
    recipients:
    - kreberl@uni-trier.de
    on_success: always
    on_failure: always
before_install: gradle installWrapper
cache:
  directories:
  - "$HOME/.m2"
  - "$HOME/.gradle"
addons:
  sonarcloud:
    organization: "lucaskreber"
    token:
     secure: "ml8fN1GHulogFpFjG8x6/ENkNBEqzwzogubr0wXLLywuBmQVa1TFZpUgPLMZr5HTuXw9VQO0IkBm6TactViWJAWTQLOwUpLEfn9OeViZIvjjeuyXdpk5MrHihPohhZHz7dgxLd7feAcl3v9OZYdDeR/54yGm6EiCwtAIXDoabiAOaPVvLsQqcL64wX8HVq6fM9dPhKN9S/Mw3rQ0jsDOtBApJsKmB9IdqCCFWpHj9WV387vcval7fQjcYsnaleMpyBjfyqQgSS/rT66LAWL4JJ7YRhG4JJfIqx0vDnRv/0RJ9k1dcYDibdiEmvYfT8IERCPosIaRwYIn7uYweKS0OZ8B/6yni6Mdp4lTxPNdQnF73SMOI3Cdqgk1RdYdtQql7oVCU1/BI1Rx+uBeBW4AUb1Is/kQW3kdd11f3EmKxji5ha/WHghGEncCMWHwXq1xL7Kc5sHCERJSdu4AojSOZlHcQft/52T0NTqiAnfGFWFKLzkwsaiQZNvPzshfj1t1ObCcR5z1z7OiO4Uw5dwa5lMUt7VWjy5bdrKlxsmDOfbozkN/KbUuKEV6NAkTVWY91Vm+AXoXTWOJJtCjKg696nDKFQc6dYB2DzkoBKWOoc1ewMHwx1k2lKUiwp9OEEfaB19TVukhU2iGi7F+J4ItlG9zvPdzfxdVKDN1x/FrVDw="
script:
- ./gradlew sonarqube

    
